//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.JSPservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicio/", ConfigurationName="JSPservice.GestionAplicacion")]
    public interface GestionAplicacion {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/LoginRequest", ReplyAction="http://Servicio/GestionAplicacion/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Proyecto1.JSPservice.LoginResponse Login(Proyecto1.JSPservice.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/LoginRequest", ReplyAction="http://Servicio/GestionAplicacion/LoginResponse")]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.LoginResponse> LoginAsync(Proyecto1.JSPservice.LoginRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/RegistrarRequest", ReplyAction="http://Servicio/GestionAplicacion/RegistrarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Proyecto1.JSPservice.RegistrarResponse Registrar(Proyecto1.JSPservice.RegistrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/RegistrarRequest", ReplyAction="http://Servicio/GestionAplicacion/RegistrarResponse")]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.RegistrarResponse> RegistrarAsync(Proyecto1.JSPservice.RegistrarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/CrearUsuarioRequest", ReplyAction="http://Servicio/GestionAplicacion/CrearUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Proyecto1.JSPservice.CrearUsuarioResponse CrearUsuario(Proyecto1.JSPservice.CrearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/CrearUsuarioRequest", ReplyAction="http://Servicio/GestionAplicacion/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.CrearUsuarioResponse> CrearUsuarioAsync(Proyecto1.JSPservice.CrearUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/ExisteUsuarioRequest", ReplyAction="http://Servicio/GestionAplicacion/ExisteUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Proyecto1.JSPservice.ExisteUsuarioResponse ExisteUsuario(Proyecto1.JSPservice.ExisteUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/GestionAplicacion/ExisteUsuarioRequest", ReplyAction="http://Servicio/GestionAplicacion/ExisteUsuarioResponse")]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.ExisteUsuarioResponse> ExisteUsuarioAsync(Proyecto1.JSPservice.ExisteUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class cuenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadUsuariosField;
        
        private string claveField;
        
        private int costoTotalServiciosField;
        
        private string emailField;
        
        private string expiracionTarjetaField;
        
        private int idCuentaField;
        
        private int idcuentaPadreField;
        
        private string nombreField;
        
        private int numeroTarjetaField;
        
        private int seguridadTarjetaField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadUsuarios {
            get {
                return this.cantidadUsuariosField;
            }
            set {
                this.cantidadUsuariosField = value;
                this.RaisePropertyChanged("cantidadUsuarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int costoTotalServicios {
            get {
                return this.costoTotalServiciosField;
            }
            set {
                this.costoTotalServiciosField = value;
                this.RaisePropertyChanged("costoTotalServicios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string expiracionTarjeta {
            get {
                return this.expiracionTarjetaField;
            }
            set {
                this.expiracionTarjetaField = value;
                this.RaisePropertyChanged("expiracionTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idCuenta {
            get {
                return this.idCuentaField;
            }
            set {
                this.idCuentaField = value;
                this.RaisePropertyChanged("idCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idcuentaPadre {
            get {
                return this.idcuentaPadreField;
            }
            set {
                this.idcuentaPadreField = value;
                this.RaisePropertyChanged("idcuentaPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int seguridadTarjeta {
            get {
                return this.seguridadTarjetaField;
            }
            set {
                this.seguridadTarjetaField = value;
                this.RaisePropertyChanged("seguridadTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string usuario, string clave) {
            this.usuario = usuario;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Proyecto1.JSPservice.cuenta @return;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Proyecto1.JSPservice.cuenta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Registrar", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class RegistrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        public RegistrarRequest() {
        }
        
        public RegistrarRequest(string nombre, string usuario, string email, string clave) {
            this.nombre = nombre;
            this.usuario = usuario;
            this.email = email;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class RegistrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public RegistrarResponse() {
        }
        
        public RegistrarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearUsuario", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class CrearUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        public CrearUsuarioRequest() {
        }
        
        public CrearUsuarioRequest(string nombre, string usuario, string email, string clave) {
            this.nombre = nombre;
            this.usuario = usuario;
            this.email = email;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearUsuarioResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class CrearUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public CrearUsuarioResponse() {
        }
        
        public CrearUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteUsuario", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class ExisteUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        public ExisteUsuarioRequest() {
        }
        
        public ExisteUsuarioRequest(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteUsuarioResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class ExisteUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ExisteUsuarioResponse() {
        }
        
        public ExisteUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestionAplicacionChannel : Proyecto1.JSPservice.GestionAplicacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionAplicacionClient : System.ServiceModel.ClientBase<Proyecto1.JSPservice.GestionAplicacion>, Proyecto1.JSPservice.GestionAplicacion {
        
        public GestionAplicacionClient() {
        }
        
        public GestionAplicacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionAplicacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAplicacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAplicacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto1.JSPservice.LoginResponse Proyecto1.JSPservice.GestionAplicacion.Login(Proyecto1.JSPservice.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Proyecto1.JSPservice.cuenta Login(string usuario, string clave) {
            Proyecto1.JSPservice.LoginRequest inValue = new Proyecto1.JSPservice.LoginRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            Proyecto1.JSPservice.LoginResponse retVal = ((Proyecto1.JSPservice.GestionAplicacion)(this)).Login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.LoginResponse> Proyecto1.JSPservice.GestionAplicacion.LoginAsync(Proyecto1.JSPservice.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto1.JSPservice.LoginResponse> LoginAsync(string usuario, string clave) {
            Proyecto1.JSPservice.LoginRequest inValue = new Proyecto1.JSPservice.LoginRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            return ((Proyecto1.JSPservice.GestionAplicacion)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto1.JSPservice.RegistrarResponse Proyecto1.JSPservice.GestionAplicacion.Registrar(Proyecto1.JSPservice.RegistrarRequest request) {
            return base.Channel.Registrar(request);
        }
        
        public bool Registrar(string nombre, string usuario, string email, string clave) {
            Proyecto1.JSPservice.RegistrarRequest inValue = new Proyecto1.JSPservice.RegistrarRequest();
            inValue.nombre = nombre;
            inValue.usuario = usuario;
            inValue.email = email;
            inValue.clave = clave;
            Proyecto1.JSPservice.RegistrarResponse retVal = ((Proyecto1.JSPservice.GestionAplicacion)(this)).Registrar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.RegistrarResponse> Proyecto1.JSPservice.GestionAplicacion.RegistrarAsync(Proyecto1.JSPservice.RegistrarRequest request) {
            return base.Channel.RegistrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto1.JSPservice.RegistrarResponse> RegistrarAsync(string nombre, string usuario, string email, string clave) {
            Proyecto1.JSPservice.RegistrarRequest inValue = new Proyecto1.JSPservice.RegistrarRequest();
            inValue.nombre = nombre;
            inValue.usuario = usuario;
            inValue.email = email;
            inValue.clave = clave;
            return ((Proyecto1.JSPservice.GestionAplicacion)(this)).RegistrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto1.JSPservice.CrearUsuarioResponse Proyecto1.JSPservice.GestionAplicacion.CrearUsuario(Proyecto1.JSPservice.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuario(request);
        }
        
        public bool CrearUsuario(string nombre, string usuario, string email, string clave) {
            Proyecto1.JSPservice.CrearUsuarioRequest inValue = new Proyecto1.JSPservice.CrearUsuarioRequest();
            inValue.nombre = nombre;
            inValue.usuario = usuario;
            inValue.email = email;
            inValue.clave = clave;
            Proyecto1.JSPservice.CrearUsuarioResponse retVal = ((Proyecto1.JSPservice.GestionAplicacion)(this)).CrearUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.CrearUsuarioResponse> Proyecto1.JSPservice.GestionAplicacion.CrearUsuarioAsync(Proyecto1.JSPservice.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto1.JSPservice.CrearUsuarioResponse> CrearUsuarioAsync(string nombre, string usuario, string email, string clave) {
            Proyecto1.JSPservice.CrearUsuarioRequest inValue = new Proyecto1.JSPservice.CrearUsuarioRequest();
            inValue.nombre = nombre;
            inValue.usuario = usuario;
            inValue.email = email;
            inValue.clave = clave;
            return ((Proyecto1.JSPservice.GestionAplicacion)(this)).CrearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto1.JSPservice.ExisteUsuarioResponse Proyecto1.JSPservice.GestionAplicacion.ExisteUsuario(Proyecto1.JSPservice.ExisteUsuarioRequest request) {
            return base.Channel.ExisteUsuario(request);
        }
        
        public bool ExisteUsuario(string usuario) {
            Proyecto1.JSPservice.ExisteUsuarioRequest inValue = new Proyecto1.JSPservice.ExisteUsuarioRequest();
            inValue.usuario = usuario;
            Proyecto1.JSPservice.ExisteUsuarioResponse retVal = ((Proyecto1.JSPservice.GestionAplicacion)(this)).ExisteUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto1.JSPservice.ExisteUsuarioResponse> Proyecto1.JSPservice.GestionAplicacion.ExisteUsuarioAsync(Proyecto1.JSPservice.ExisteUsuarioRequest request) {
            return base.Channel.ExisteUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto1.JSPservice.ExisteUsuarioResponse> ExisteUsuarioAsync(string usuario) {
            Proyecto1.JSPservice.ExisteUsuarioRequest inValue = new Proyecto1.JSPservice.ExisteUsuarioRequest();
            inValue.usuario = usuario;
            return ((Proyecto1.JSPservice.GestionAplicacion)(this)).ExisteUsuarioAsync(inValue);
        }
    }
}
